### ISSUE TITLE
Add Thymeleaf support to work with Spring 5

### ISSUE THREAD

**Issue by LucieFaire** [resource4j/resource4j#42]
Migration to Spring Boot 2 and thymeleaf-spring5 returns the exception:

	public ITemplateEngine defaultTemplateEngine() {
		TemplateEngine engine = new TemplateEngine();
		engine.setDialect(new SpringStandardDialect());
		engine.setTemplateResolver(defaultTemplateResolver());
		engine.setMessageResolver(messageResolver());
		return new Resource4jTemplateEngine(engine);
	}
` java.lang..NoClassDefFoundError: org.thymeleaf.spring4.dialect.SpringStandardDialect`

**Comment by ivan-gammel** [comment]
Done
